"""
Synthetic Brownian-motion substrate bank for testing and comparison experiments.

Real substrates (packed cylinders / spheres from dmipy-sim) are generated by
the offline build_bank.py script. This module provides a fast in-memory
approximation using free Gaussian diffusion steps — suitable for unit tests
and the MC-bias comparison experiment but not for biological ground truth.

Usage
-----
    from dmipy_design.substrate_bank_synthetic import make_synthetic_bank
    bank = make_synthetic_bank(n_walkers=2000, n_t=201, dt=1e-4)
    # bank.entries[0].trajectories.shape -> (2000, 201, 3)
"""

from __future__ import annotations

import numpy as np

try:
    import jax.numpy as jnp
    _JAX_AVAILABLE = True
except ImportError:
    _JAX_AVAILABLE = False

from .substrate_bank import SubstrateBank, SubstrateEntry


def make_synthetic_bank(
    n_walkers: int = 2000,
    n_t: int = 201,
    dt: float = 1e-4,
    seed: int = 42,
    D: float = 2e-9,
) -> SubstrateBank:
    """Generate a synthetic free-diffusion substrate bank.

    Trajectories are simulated as free Brownian motion (Gaussian steps) — no
    geometric boundaries. This provides a zero-bias reference: any analytical
    Ball (isotropic free diffusion) model should match the MC signal closely,
    while restricted-diffusion models (cylinder, sphere) will show bias.

    Parameters
    ----------
    n_walkers : int
        Number of random walkers.
    n_t : int
        Number of time steps (trajectory length including t=0).
    dt : float
        Time step in seconds.
    seed : int
        Random seed for reproducibility.
    D : float
        Free diffusion coefficient in m²/s (default: 2×10⁻⁹ m²/s, CSF-like).

    Returns
    -------
    SubstrateBank with one entry: 'synthetic_free'.

    Notes
    -----
    theta_nominal is [D] — a length-1 vector for use with a simple isotropic
    forward function f(theta, scheme) -> exp(-b * theta[0]).
    When using with dmipy Ball model or ball_forward wrappers, you may need
    to adapt theta_nominal to the exact parameter order expected.
    """
    if not _JAX_AVAILABLE:
        raise ImportError("JAX is required for make_synthetic_bank.")

    rng = np.random.default_rng(seed)
    sigma_step = np.sqrt(2.0 * D * dt)

    # Brownian steps: (n_walkers, n_t, 3)
    steps = rng.normal(0.0, sigma_step, size=(n_walkers, n_t, 3)).astype(np.float32)
    # Cumulative sum -> positions (first step = 0 displacement start)
    trajectories = np.cumsum(steps, axis=1).astype(np.float32)

    # Nominal theta: [D]  — used by simple ball_forward(theta, scheme) = exp(-b*D)
    theta_nominal = jnp.array([D], dtype=jnp.float32)

    entry = SubstrateEntry(
        substrate_id="synthetic_free",
        trajectories=jnp.array(trajectories),
        dt_traj=dt,
        theta_nominal=theta_nominal,
        biological_weight=1.0,
        walker_weights=None,
        meta={
            "type": "synthetic_brownian",
            "D_m2s": D,
            "n_walkers": n_walkers,
            "n_t": n_t,
            "dt_s": dt,
        },
    )

    return SubstrateBank([entry])
